config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  namespace :admin do
    resources :news_versions
  end

  get 'news_versions/activate_version' => 'admin/news_versions#activate_version'
  get 'news_versions/remove_draft' => 'admin/news_versions#remove_draft'

  patch '/admin/news_versions' => 'admin/news_versions#update'
  put '/admin/news_versions' => 'admin/news_versions#update'

  post 'news_versions/create_comment' => 'admin/news_versions#create_comment', as: :news_comments

  root 'admin/news_versions#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :news
end

app/models/news.rb
class News < ApplicationRecord

  has_many :news_versions, dependent: :destroy

  accepts_nested_attributes_for :news_versions, allow_destroy: true

  before_create :set_number

  private

  def set_number
    self.number = News.count > 0 ? News.last.number + 1 : 1
  end

end

app/models/news_version.rb
class NewsVersion < ApplicationRecord
  has_attached_file :image, styles: { large: '600x600', medium: '300x300', thumb: '100x100' }, default_url: 'https://ichef.bbci.co.uk/news/1024/media/images/48351000/gif/_48351569_640x360-news.gif'
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  belongs_to :news

  before_create :set_dates
  before_update :set_updated_at

  private

  def set_dates
    self.created_at = DateTime.now
    self.updated_at = DateTime.now
  end

  def set_updated_at
    self.updated_at = DateTime.now
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/news_versions_controller.rb
class Admin::NewsVersionsController < ApplicationController
  before_action :set_news_version, only: [:show, :edit, :destroy]

  def index
    @current_user = current_user
    @news_versions = NewsService.get_news_versions(@current_user)
  end

  def show
    @comment = Comment.new
    @comment.news_id = @news.id
    @news_comments = Comment.where(news_id: @news.id)
  end

  def new
    @current_user = current_user
    @news = News.new
    @news.created_at = DateTime.now
    if current_user.is_admin
      @news.news_versions.build.is_draft = false
    else
      @news.news_versions.build   #draft is true by default
    end

  end

  def edit
    @current_user = current_user
  end

  def create
    @news = News.new(news_version_params)
    respond_to do |format|
      if @news.save
        @news.update(news_version_id: NewsVersion.last.id) if NewsVersion.last.active == true
        format.html { redirect_to admin_news_version_path(version_from_news(@news.news_version_id)), notice: 'News version was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    if current_user.is_admin    #if admin edits version
      @news = News.find(params[:news]['id'])
      version_params = NewsService.set_draft_and_active(news_version_params)
      respond_to do |format|
        if @news.update(version_params)
          NewsService.update_version_id_in_news(@news)
          format.html { redirect_to admin_news_version_path(version_from_news(@news.news_version_id)), notice: 'News version was successfully updated.' }
        else
          format.html { render :edit }
        end
      end
    else
      NewsService.create_new_version(news_version_params)   #if authorized user edits version, not admin
      redirect_to admin_news_versions_path
    end
  end

  def destroy
    @news_version = NewsVersion.find(params[:id])
    respond_to do |format|
      if @news_version.update(mark_for_deletion: true)
        format.html { redirect_to admin_news_version_path(@news_version), notice: 'News version was successfully marked for deletion' }
        format.json { render :show, status: :ok, location: @news_version }
      else
        format.html { render :edit }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  def activate_version
    @version = NewsVersion.find(params[:id])
    if @version.update(active: true)
      @version.news.update(news_version_id: @version.id)
    end
    @current_user = current_user
    @news_versions = NewsService.get_news_versions(@current_user)
    render :index
  end

  def remove_draft
    NewsVersion.find(params[:id]).update(is_draft: false)
    @current_user = current_user
    @news_versions = NewsService.get_news_versions(@current_user)
    render :index
  end

  def create_comment
    @comment = Comment.new(comment_params)
    respond_to do |format|
      if @comment.save
        format.html { redirect_to admin_news_version_path(version_from_news(@comment.news.news_version_id)), notice: 'Comment was successfully created.' }
      else
        format.html { render :show }
      end
    end
  end

  private

    def set_news_version
      @news_version = NewsVersion.find(params[:id])
      @news = @news_version.news
    end

    def version_from_news(id)
      NewsVersion.find(id)
    end

    def news_version_params
      params.require(:news).permit(:id, :number,
                                   news_versions_attributes: [:id, :news_id, :title, :content, :published_at, :is_draft, :active, :image, :created_at, :updated_at, :_destroy])
    end

    def comment_params
    params.require(:comment).permit(:id, :news_id, :comment)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/news_versions_controller.rb
class NewsVersionsController < ApplicationController
  before_action :set_news_version, only: [:show, :edit, :update, :destroy]

  # GET /news_versions
  # GET /news_versions.json
  def index
    @news_versions = NewsVersion.all
  end

  # GET /news_versions/1
  # GET /news_versions/1.json
  def show
  end

  # GET /news_versions/new
  def new
    @news_version = NewsVersion.new
  end

  # GET /news_versions/1/edit
  def edit
  end

  # POST /news_versions
  # POST /news_versions.json
  def create
    @news_version = NewsVersion.new(news_version_params)

    respond_to do |format|
      if @news_version.save
        format.html { redirect_to @news_version, notice: 'News version was successfully created.' }
        format.json { render :show, status: :created, location: @news_version }
      else
        format.html { render :new }
        format.json { render json: @news_version.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news_versions/1
  # PATCH/PUT /news_versions/1.json
  def update
    respond_to do |format|
      if @news_version.update(news_version_params)
        format.html { redirect_to @news_version, notice: 'News version was successfully updated.' }
        format.json { render :show, status: :ok, location: @news_version }
      else
        format.html { render :edit }
        format.json { render json: @news_version.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news_versions/1
  # DELETE /news_versions/1.json
  def destroy
    @news_version.destroy
    respond_to do |format|
      format.html { redirect_to news_versions_url, notice: 'News version was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news_version
      @news_version = NewsVersion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def news_version_params
      params.require(:news_version).permit(:news_id, :title, :content, :published_at, :post_type_id, :created_at, :updated_at)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/news_versions_helper.rb
module NewsVersionsHelper
end

app/views/admin/news_versions/_form.html.erb
<%= form_with(model: news, local: true, html: { multipart: true },  url: admin_news_versions_path) do |news_form| %>
  <% if news.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(news_version.errors.count, 'error') %> prohibited this news_version from being saved:</h2>
      <ul>
      <% news.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
      <%= news_form.label :number %>
      <%= news_form.text_field :number, id: :news_number %>
    </div>

    <%= news_form.hidden_field :id, value: @news.id %>

    <%= news_form.fields_for :news_versions do |form| %>

    <div class="field">
      <%= form.label :title %>
      <%= form.text_field :title, id: :news_version_title %>
    </div>

     <div class="field">
      <%= form.label :content %>
      <%= form.text_field :content, id: :news_version_content %>
    </div>

    <div class="field">
      <%= form.label :published_at %>
      <%= form.datetime_select :published_at, id: :news_version_published_at %>
    </div>

    <div class="field">
      <%= form.label :image %>
      <%= form.file_field :image %>
    </div>

  <% end %>

  <div class="actions">
    <%= news_form.submit %>
  </div>
<% end %>

app/views/admin/news_versions/edit.html.erb
<h1>Editing News Version</h1>

<%= render 'form', news: @news %>

<%= link_to 'Show', admin_news_version_path(@news_version) %> |
<%= link_to 'Back', admin_news_versions_path %>

app/views/admin/news_versions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>News Versions</h1>

<table>
  <thead>
    <tr>
      <th>News id</th>
      <th>version id</th>
      <th>Title</th>
      <th>Content</th>
      <th>Published at</th>
      <th>Created at</th>
      <th>Updated at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @news_versions.each do |news_version| %>
      <tr>
        <td><%= news_version.news.id %></td>
        <td><%= news_version.id %></td>
        <td><%= news_version.title %></td>
        <td><%= news_version.content %></td>
        <td><%= news_version.published_at %></td>
        <td><%= news_version.created_at %></td>
        <td><%= news_version.updated_at %></td>
        <td><%= link_to 'Show', admin_news_version_path(news_version) %></td>
        <% if user_signed_in? %>
          <td><%= link_to 'Edit', edit_admin_news_version_path(news_version, id: news_version.id) %></td>
            <% if @current_user.is_admin %>
                <% if news_version.active == false %>
                    <td><%= link_to 'Activate', news_versions_activate_version_path(id: news_version.id) %></td>
                <% end %>
                <% if news_version.is_draft == true %>
                    <td><%= link_to 'Remove Draft State', news_versions_remove_draft_path(id: news_version.id)  %></td>
                <% end %>
                <td><%= link_to 'Destroy', admin_news_version_path(news_version), method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% end %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if user_signed_in? %>
<%= link_to 'New Version', new_admin_news_version_path %>
<% end %>

app/views/admin/news_versions/new.html.erb
<h1>New News Version</h1>

<%= render 'form', news: @news %>

<%= link_to 'Back', admin_news_versions_path %>

app/views/admin/news_versions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>News:</strong>
  <%= @news_version.news.number %>
</p>

<p>
  <strong>Title:</strong>
  <%= @news_version.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @news_version.content %>
</p>

<p>
  <strong>Published at:</strong>
  <%= @news_version.published_at %>
</p>

<p>
  <strong>Created at:</strong>
  <%= @news_version.created_at %>
</p>

<p>
  <strong>Updated at:</strong>
  <%= @news_version.updated_at %>
</p>


<% if @news_comments.present? %>
    <h4>comments:</h4>
    <% @news_comments.each.with_index do |item, index| %>
      <p><%= index + 1 %>. <%= item.comment %></p>
    <% end %>
<% end %>
<br>

<%= form_with(model: @comment, local: true, url: news_comments_path) do |form| %>
        <%= form.hidden_field :news_id  %>

        <div class="field">
          <%= form.text_field :comment %>
        </div>

    <div class="actions">
      <%= form.submit %>
    </div>
<% end %>

<%= link_to 'Edit', edit_admin_news_version_path(@news_version) %> |
<%= link_to 'Back', admin_news_versions_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NewsSite</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% if user_signed_in? %>
        <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
  <% else %>
        <%= link_to('Login', new_user_session_path)  %>
        <%= link_to 'Sign up', new_user_registration_path %>
  <% end %>

  <%= yield %>
  </body>
</html>

app/views/news_versions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>News Versions</h1>

<table>
  <thead>
    <tr>
      <th>News</th>
      <th>Title</th>
      <th>Content</th>
      <th>Published at</th>
      <th>Post type</th>
      <th>Created at</th>
      <th>Updated at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @news_versions.each do |news_version| %>
      <tr>
        <td><%= news_version.news %></td>
        <td><%= news_version.title %></td>
        <td><%= news_version.content %></td>
        <td><%= news_version.published_at %></td>
        <td><%= news_version.post_type %></td>
        <td><%= news_version.created_at %></td>
        <td><%= news_version.updated_at %></td>
        <td><%= link_to 'Show', news_version %></td>
        <td><%= link_to 'Edit', edit_news_version_path(news_version) %></td>
        <td><%= link_to 'Destroy', news_version, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New News Version', new_news_version_path %>

app/views/news_versions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>News:</strong>
  <%= @news_version.news %>
</p>

<p>
  <strong>Title:</strong>
  <%= @news_version.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @news_version.content %>
</p>

<p>
  <strong>Published at:</strong>
  <%= @news_version.published_at %>
</p>

<p>
  <strong>Post type:</strong>
  <%= @news_version.post_type %>
</p>

<p>
  <strong>Created at:</strong>
  <%= @news_version.created_at %>
</p>

<p>
  <strong>Updated at:</strong>
  <%= @news_version.updated_at %>
</p>

<%= link_to 'Edit', edit_news_version_path(@news_version) %> |
<%= link_to 'Back', news_versions_path %>